require File.expand_path('../../lib/parking_lot', __FILE__)
require File.expand_path('../../lib/car', __FILE__)
require File.expand_path('../../lib/ticket', __FILE__)
require File.expand_path('../../lib/boy', __FILE__)
require File.expand_path('../../lib/smart_boy', __FILE__)